### ISSUE TITLE
Split y-axis (date) by Taxonomy on CSV export

### ISSUE THREAD

**Issue by UserCentrix** [CodeAtCode/Woocommerce-Taxonomy-Report#3]
Hello,

This plugin is wonderful and is exactly what I have been looking for (looking hard for a long time).

However, when exporting, rather than each taxonomy term value being on the same line for each date, instead each are stacked above one-another with the dates repeated. Please see attached file. 

[report-7day-2018-07-25.zip](https://github.com/CodeAtCode/Woocommerce-Taxonomy-Report/files/2229713/report-7day-2018-07-25.zip)

I am happy to make a donation if you are able to clean up the export file so that comparisons can be made across the y-axis of the table.

Please let me know if you are able to assist.

Many thanks

**Comment by Mte90** [comment]
Hi Usercentrix,
we never checked how worked the csv export and you are right is not so good. 
Seems that is like is by block.
We have to see how we can alter the csv export, because csv is only one sheet so we cannot do multiple of them but an unique page with all the info, so we needto see how to structure it.

**Comment by UserCentrix** [comment]
Thank you for your very quick response. Very encouraging. I look forward to an update. Please let me know if I can help in any way. This is a great plugin and we have been unable to find anything like it, and so I am happy to contribute to support development.

**Comment by Mte90** [comment]
I have to close it because the Woocommerce api doesn't allow to do that easily.
